### ISSUE TITLE
Issue with LDAP authentication on ubi8/node-js docker image version > 12

### ISSUE THREAD

**Issue by aravindan06** [hardillb/node-red-contrib-ldap-auth#18]
I am utilizing this node to do LDAP authentication for Node-Red. It is working well with node-js:12 ubi8 image. When we go with node-js:14 or later version, LDAP unbind is not happening so connection closed exception occurring. Tried to upgrade ldapjs from 1.0.2 to 2.3.3 version still didn't help.

Can you please advise.

**Error Stack:**

8 Oct 10:47:23 - [red] Uncaught Exception:
8 Oct 10:47:23 - [error] ConnectionError: 2__ldaps://xxxxxxxxxxxxxxxxxx:636 closed
    at /opt/app-root/src/node_modules/ldapjs/lib/client/client.js:1277:17
    at Array.forEach (<anonymous>)
    at Client._onClose (/opt/app-root/src/node_modules/ldapjs/lib/client/client.js:1272:19)
    at TLSSocket.d (/opt/dynatrace/oneagent/agent/bin/1.267.171.20230713-194652/any/nodejs/nodejsagent.js:4551:23)
    at dynatraceOnServiceExecutionIndicator (/opt/dynatrace/oneagent/agent/bin/1.267.171.20230713-194652/any/nodejs/nodejsagent.js:3125:20)
    at a.safeInvoke (/opt/dynatrace/oneagent/agent/bin/1.267.171.20230713-194652/any/nodejs/nodejsagent.js:3182:41)
    at TLSSocket.<anonymous> (/opt/dynatrace/oneagent/agent/bin/1.267.171.20230713-194652/any/nodejs/nodejsagent.js:6637:21)
    at TLSSocket.emit (node:events:514:28)
    at node:net:323:12
    at TCP.done (node:_tls_wrap:588:7)

Thanks

**Comment by hardillb** [comment]
Sorry, not sure what is happening here.

The code as shipped (with the original version of ldap.js) is working just fine for me on NodeJS 16
